// firebase/admin.ts — admin-context Firestore actions (member activation,
// deletion, claims, payouts). Read-side admin dashboards use the hooks in
// src/hooks/ (useAdminStats, useAdminCommissions, useAdminPayouts) which query
// the publicProfiles mirror; the old direct getDashboardStats/getTopRecruiters
// fetchers were removed in favor of those.
import {
    collection,
    getDocs,
    getDoc,
    doc,
    updateDoc,
    setDoc,
    deleteDoc,
    serverTimestamp,
    query,
    where,
    limit as limitQuery,
    writeBatch,
} from "firebase/firestore";
import { db } from "./config";
import { triggerCommissions, type Package } from "./commissions";
import { writePublicProfile, deletePublicProfile } from "./publicProfiles";
import { releaseMobile } from "./phoneRegistry";

// --- MEMBERS ---
export const getAllMembers = async () => {
    const q = query(collection(db, "members"), where("isAdmin", "==", false));
    const snap = await getDocs(q);
    return snap.docs.map((d) => ({ uid: d.id, ...d.data() }));
};

const generateReferralCode = (): string => {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    const segment = (len: number) =>
        Array.from({ length: len }, () => chars[Math.floor(Math.random() * chars.length)]).join("");
    return `${segment(4)}-${segment(4)}-${segment(4)}`;
};

export const activateMember = async (uid: string) => {
    const memberSnap = await getDoc(doc(db, "members", uid));
    if (!memberSnap.exists()) return;

    const memberData = memberSnap.data();
    const now = new Date();

    const dateExpiry = new Date(now);
    dateExpiry.setFullYear(dateExpiry.getFullYear() + 1);

    const dateContestabilityEnd = new Date(now);
    dateContestabilityEnd.setMonth(dateContestabilityEnd.getMonth() + 1);

    const isFirstActivation = !memberData.referralCode;

    if (isFirstActivation) {
        const referralCode = generateReferralCode();
        await updateDoc(doc(db, "members", uid), {
            status: "active",
            referralCode,
            dateActivated: serverTimestamp(),
            dateEligibility: serverTimestamp(),
            dateExpiry,
            dateContestabilityEnd,
            packageLocked: false,
        });
        await setDoc(doc(db, "referralCodes", referralCode), { uid });

        // Mirror activation + the freshly-issued referral code to the public profile.
        await writePublicProfile(uid, { status: "active", referralCode });

        const pkg = memberData.package as Package | null;
        if (pkg) await triggerCommissions(uid, pkg);
    } else {
        await updateDoc(doc(db, "members", uid), {
            status: "active",
            dateActivated: serverTimestamp(),
            dateEligibility: serverTimestamp(),
            dateExpiry,
            dateContestabilityEnd,
            packageLocked: false,
        });

        await writePublicProfile(uid, { status: "active" });
    }
};

// --- DELETE (super-admin actions) ---

// Checks whether a member is safe to hard-delete (no downlines, no commissions).
export const getMemberDependencies = async (uid: string) => {
    const [downlineSnap, earnedSnap, fromSnap] = await Promise.all([
        getDocs(query(collection(db, "members"), where("referredBy", "==", uid), limitQuery(1))),
        getDocs(query(collection(db, "commissions"), where("earnedBy", "==", uid), limitQuery(1))),
        getDocs(query(collection(db, "commissions"), where("fromMember", "==", uid), limitQuery(1))),
    ]);
    return {
        hasDownlines: !downlineSnap.empty,
        hasCommissions: !earnedSnap.empty || !fromSnap.empty,
    };
};

// Hard delete: permanently removes the member doc (+ their referral-code mapping).
// Caller MUST verify there are no dependents first (getMemberDependencies).
// NOTE: the Firebase Auth login itself can't be removed client-side on Spark —
// that needs the Admin SDK (Blaze).
export const hardDeleteMember = async (uid: string) => {
    const snap = await getDoc(doc(db, "members", uid));
    const code = snap.exists() ? (snap.data().referralCode as string | undefined) : undefined;
    const mobile = snap.exists() ? (snap.data().mobile as string | undefined) : undefined;
    if (code) {
        await deleteDoc(doc(db, "referralCodes", code)).catch(() => {});
    }
    await deleteDoc(doc(db, "members", uid));
    await deletePublicProfile(uid).catch(() => {});
    // Free the mobile so the person can register again (one-account policy).
    if (mobile) await releaseMobile(mobile);
};

// Force delete: cascade-removes the member, their referral-code mapping, AND every
// commission doc tied to them (both earned by them and generated by their payment).
// Use for clearing test data — destroys commission history. Caller should still
// block members with downlines to avoid orphaning the tree.
export const forceDeleteMember = async (uid: string) => {
    const [earnedSnap, fromSnap] = await Promise.all([
        getDocs(query(collection(db, "commissions"), where("earnedBy", "==", uid))),
        getDocs(query(collection(db, "commissions"), where("fromMember", "==", uid))),
    ]);
    const commissionIds = new Set<string>();
    earnedSnap.forEach((d) => commissionIds.add(d.id));
    fromSnap.forEach((d) => commissionIds.add(d.id));
    await Promise.all([...commissionIds].map((id) => deleteDoc(doc(db, "commissions", id)).catch(() => {})));

    await hardDeleteMember(uid);
};

// Sends a Firebase password-reset email so the member can set a new password.
// Only works for members with a REAL email. Members encoded with a synthetic
// (mobile-based) login can't receive this — that needs the Blaze/Cloud Functions
// upgrade (an Admin-SDK reset). Throws if no email.
export const sendMemberPasswordReset = async (email: string) => {
    const { getAuth, sendPasswordResetEmail } = await import("firebase/auth");
    await sendPasswordResetEmail(getAuth(), email);
};

// --- CLAIMS ---

// Move a submitted claim into review (no decision recorded yet).
export const setClaimUnderReview = async (claimId: string) => {
    await updateDoc(doc(db, "claims", claimId), { status: "under_review" });
};

// Record a decision (approved/rejected/released) and stamp when it was decided.
export const updateClaimStatus = async (claimId: string, status: "approved" | "rejected" | "released") => {
    await updateDoc(doc(db, "claims", claimId), {
        status,
        dateDecided: serverTimestamp(),
    });
};

// --- PAYOUTS ---

// Admin confirms a payout was sent (money + proof handed over offline). This
// also marks every commission the payout covers as "paid".
export const markPayoutSent = async (payoutId: string, reference: string) => {
    const payoutSnap = await getDoc(doc(db, "payouts", payoutId));
    const commissionIds: string[] = payoutSnap.exists() ? (payoutSnap.data().commissionIds ?? []) : [];

    const batch = writeBatch(db);
    batch.update(doc(db, "payouts", payoutId), {
        status: "sent",
        reference,
        dateSent: serverTimestamp(),
    });
    for (const id of commissionIds) {
        batch.update(doc(db, "commissions", id), { status: "paid" });
    }
    await batch.commit();
};

// Admin rejects a payout request — the covered commissions are released back to
// "pending" so the member can claim them again.
export const rejectPayout = async (payoutId: string, reason: string = "") => {
    const payoutSnap = await getDoc(doc(db, "payouts", payoutId));
    const commissionIds: string[] = payoutSnap.exists() ? (payoutSnap.data().commissionIds ?? []) : [];

    const batch = writeBatch(db);
    batch.update(doc(db, "payouts", payoutId), { status: "rejected", reason, dateSent: null });
    for (const id of commissionIds) {
        batch.update(doc(db, "commissions", id), { status: "pending", payoutId: null });
    }
    await batch.commit();
};
